#!/usr/bin/env bash

# Load modified map keyboard
setxkbmap -I ~/dotfiles/xkb isodev -print | xkbcomp -w 3 -I$HOME/dotfiles/xkb - $DISPLAY

# Disable PC Speaker Beep
xset -b

# http://catern.com/2014/12/20/plain-text-configuration-gnome.html
# to find more settings see dconf-editor
#cat ~/dotfiles/gtk-3.0/user.conf | dconf load /
