{ pkgs, lib, inputs, ... }:

{

  imports = [
    inputs.nixos-hardware.nixosModules.lenovo-thinkpad-x1-9th-gen
    inputs.disko.nixosModules.disko
    ./beta-disk.nix
  ];

  networking.wireless.interfaces = [ "wlp0s20f3" ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Needed when typing in passwords for full disk encryption
  console.earlySetup = lib.mkDefault true;

  # Enable touchpad, for options
  # see https://nixos.org/nixos/options.html#libinput
  services.libinput.enable = true;

  # https://github.com/NixOS/nixpkgs/pull/62101
  services.throttled.enable = true;

  # hardware.cpu.intel.updateMicrocode = true;

  # https://nixos.wiki/wiki/Accelerated_Video_Playback
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-media-driver
    ];
  };

  hardware.enableAllFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;

  environment.systemPackages = [ pkgs.vulkan-validation-layers ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Generated by `nixos-generate-config --show-hardware-config --no-filesystems`

  boot.kernelModules = [
    "kvm-intel"
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "usbhid" "sd_mod" ];

}
