{ config, pkgs, lib, modulesPath, ... }:
{

  networking.wireless.interfaces = [ "wlp82s0" ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # https://github.com/NixOS/nixos-hardware/blob/master/common/pc/laptop/acpi_call.nix
  boot.kernelModules = [ "acpi_call" "kvm-intel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  # Enable touchpad, for options
  # see https://nixos.org/nixos/options.html#libinput
  services.xserver.libinput.enable = true;

  # https://github.com/NixOS/nixpkgs/pull/62101
  services.throttled.enable = true;

  hardware.cpu.intel.updateMicrocode = true;

  # https://nixos.wiki/wiki/Accelerated_Video_Playback
  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-media-driver
    ];
  };
  hardware.enableAllFirmware = true;

  # ====
  # ====
  # Generated by ‘nixos-generate-config’
  # ====
  # ====

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/817d1c98-800e-43d7-98d5-cc42cced6e7d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/39F5-E3A8";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/e03068e2-c65c-4872-9a57-4db835d28917"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
