#!/usr/bin/env fish


if test $argv[1]
    set sleep_time $argv[1]
else
    set sleep_time 3s
end
# sleep $sleep_time; and notify-send -i /run/current-system/sw/share/icons/Paper/48x48/status/dialog-warning.png "TIMEOUT after $sleep_time !!"
sleep $sleep_time; and zenity --info --timeout 5 --text "<span foreground='black' font='24px'>TIMEOUT after $sleep_time !!</span>"


# vim: filetype=fish
