# This file has been generated by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, buildNeovimPluginFrom2Nix, fetchFromGitHub, fetchgit }:

final: prev:
{
  baleia-nvim = buildVimPluginFrom2Nix {
    pname = "baleia.nvim";
    version = "2022-05-17";
    src = fetchFromGitHub {
      owner = "m00qek";
      repo = "baleia.nvim";
      rev = "af6a17b21336599df8f17a8c1186b414330b8b44";
      sha256 = "063xhhy5ln1yvwfapv5r8b17sdcspszw5xghgkjk21nnssp4yk2v";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/m00qek/baleia.nvim/";
  };

  nterm-nvim = buildVimPluginFrom2Nix {
    pname = "nterm.nvim";
    version = "2022-05-10";
    src = fetchFromGitHub {
      owner = "jlesquembre";
      repo = "nterm.nvim";
      rev = "cd7b7035d09144ee4ea49244bf5cb8ed68e499f8";
      sha256 = "0cvg03d1z7jkamg062ng731pdmckrdm611q24brr9ha1qc5q26gm";
    };
    meta.homepage = "https://github.com/jlesquembre/nterm.nvim/";
  };

  telescope-live-grep-args-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-live-grep-args.nvim";
    version = "2022-08-27";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-live-grep-args.nvim";
      rev = "32b633b062d1168a2d18ad27994e5b4ef97f0a74";
      sha256 = "0nsf6xxvqbkm83bv8bcyxr71w3nbbs1qx2z0sqj5kd831amgd62g";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-live-grep-args.nvim/";
  };


}
