name: "Update deps"
on:
  schedule:
    - cron: "27 2 * * 3"

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: latest

      - name: Update clj dependencies
        run:
          clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version
          "RELEASE"}}}' -M -m antq.core -d dotfiles/clojure --upgrade --force
          --skip=github-action

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          commit-message: Update clojure dependencies
          title: Update clojure dependencies
          assignees: jlesquembre
          branch: update-clj-deps

  neovim-plugins:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18

      - name: Check plugin updates
        run: "nix run .#update-vim-plugins"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          commit-message: Update nvim plugins
          title: Update neovim plugins
          assignees: jlesquembre
          branch: update-nvim-deps
