name: "Update NixOS"
on:
  push:

jobs:
  update-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Free disk space
        run: .github/free_disk_space.sh

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install Cachix
        uses: cachix/cachix-action@v10
        with:
          name: jl-nix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build old NixOS
        run: |
          nix build -o /tmp/old_system .#nixosConfigurations.beta.config.system.build.toplevel

      - name: Update flake.nix
        run: |
          nix flake update

      - name: Build new NixOS
        run: |
          nix build -o /tmp/new_system .#nixosConfigurations.beta.config.system.build.toplevel

      - name: Get NixOS diff
        id: get-pr-body
        run: |
          nix run github:NixOS/nixpkgs/nixos-unstable#nvd -- --color never diff /tmp/old_system /tmp/new_system > /tmp/pr-body.txt
          body=$(cat /tmp/pr-body.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          body: ${{ steps.get-pr-body.outputs.body }}
          commit-message: Update flake.nix
          title: Update flake.nix
          assignees: jlesquembre
          branch: update-flake-nix
