name: "Update nvim deps"
on:
  # schedule:
  #   - cron: "9 5 * * 2"
  push:
    branches:
      - master

jobs:
  neovim-plugins:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check plugin updates
        run: nix-shell --command update-vim-plugins shell-nvim.nix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: Update nvim plugins
          title: Update neovim plugins
          assignees: jlesquembre
          branch: update-nvim-deps
