on:
  schedule:
    - cron: "1 5 * * 2"

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Update clj dependencies
        run:
          clojure -Sdeps '{:deps {olical/depot {:mvn/version "LATEST"}}}' -m
          depot.outdated.main --update clojure/deps.edn
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update clojure dependencies
          title: Update clojure dependencies
          assignees: jlesquembre
          branch: update-clj-deps
